[build]
  command = "npm run build"  # o el comando que usas para construir tu proyecto
  functions = "functions"  # el directorio donde se encuentran tus funciones

[functions]
  main_function = "functions/main_function.js"
  polyfills_function = "functions/polyfills_function.js"
  runtime_function = "functions/runtime_function.js"
